### ISSUE TITLE
Block volume functions from heketi api

### ISSUE THREAD

**Issue by phlogistonjohn** [vponomaryov/heketi-rally-plugin#1]
Heketi's python api now supports some block volume APIs. Instead of having an independent implementation for these APIs, this library should use the one from heketi directly (when possible).

For example:
https://github.com/heketi/heketi/blob/master/client/api/python/heketi/heketi.py#L256

**Comment by vponomaryov** [comment]
Thank you, John. Will update it.

**Comment by vponomaryov** [comment]
Fixed in following commit: https://github.com/vponomaryov/heketi-rally-plugin/commit/46386622
